name: Build and Deploy Docker Image

# Disparar acciones en push a las ramas 'develop' o 'master'
on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        if [ "${{ github.ref }}" == "refs/heads/master" ]; then
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mi-api-node:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mi-api-node:latest
        elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mi-api-node:develop .
          docker push ${{ secrets.DOCKER_USERNAME }}/mi-api-node:develop
        fi

    - name: Image digest
      run: echo ${{ steps.docker.outputs.digest }}

