#NA
name: Build and Deploy Docker Image

# Disparar acciones solo cuando se complete un pull request en la rama master
on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true  # Asegurarse de que se ejecute solo cuando el PR ha sido mergeado
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mi-api-node:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/mi-api-node:latest

    - name: Image digest
      run: echo ${{ steps.docker.outputs.digest }}
